# Generated by Django 3.1.4 on 2020-12-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
